# Generated by Django 3.2.8 on 2021-10-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, verbose_name='title')),
                ('description', models.CharField(max_length=300000, verbose_name='description')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
