
# Register Api

POST http://127.0.0.1:8000/api/v1/api-token-auth/
content-type: application/json

{
  "username": "admin",
  "password": "HkhG7thb"
}

# Create /list User POST/GET
###

POST   http://127.0.0.1:8000/api/v1/user/ HTTP/1.1
content-type: application/json
Authorization: token 0cb45bf516583d90c1edb9c55c6a19c577e86485
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsI

{
  "username": "Plavr1",
  "email": "plavr1@mail.ru",
  "password": "HkhG7thb"
}

###

POST https://llgall.ga/api/v1/api-token-auth/

content-type: application/json

{
  "username": "admin",
  "password": "HkhG7thb"
}

###

GET ws://llgall.ga/main_view/test